module.exports = {
	commonunits: {},
	deploy: {},
	chooseaction: {},
	changeunit: {},
	differentunits: {},
	changeowners: {},
	asymmetric: {},
	multiplegoals: {},
	multiplesteps: {},
	infiltrate: {},
	kingkill: {},
	push: {},
	formation: {},
	shoot: {},
	directions: {},
	custodian: {},
	starve: {},
	eradicate: {},
	terrain: {},
	capture: {},
	promote: {},
	repeat: {},
	jump: {},
	limitmoves: {}
};